const countryList = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua andarbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia,lurinational State of",
  "Bonaire,int Eustatius and Saba",
  "Bosnia anderzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indiancean Territory",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Cayman Islands",
  "Central Africanepublic",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (KeelingIslands)",
  "Colombia",
  "Comoros",
  "Congo",
  "Congo,he Democratic Republic of the",
  "Cook Islands",
  "Costa Rica",
  "C\u00f4te'Ivoire",
  "Croatia",
  "Cuba",
  "Cura\u00e7ao",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Ethiopia",
  "Falkland IslandsMalvinas)",
  "Faroe Islands",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southernerritories",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Islandnd McDonald Islands",
  "Holy SeeVatican City State)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran,slamic Republic of",
  "Iraq",
  "Ireland",
  "Isle ofan",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea,emocratic People's Republic of",
  "Korea,epublic of",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People Democratic Republic",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Macedonia,he Former Yugoslav Republic of",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia,ederated States of",
  "Moldova,epublic of",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Marianaslands",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine,tate of",
  "Panama",
  "Papua Newuinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "R\u00e9union",
  "Romania",
  "Russian Federation",
  "Rwanda",
  "Saint Barth00e9lemy",
  "Saint HelenaAscension and Tristan da Cunha",
  "Saint Kittsnd Nevis",
  "Saint Lucia",
  "Saint MartinFrench part)",
  "Saint Pierrend Miquelon",
  "Saint Vincentnd the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tomend Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint MaartenDutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgiand the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Svalbard andan Mayen",
  "Swaziland",
  "Sweden",
  "Switzerland",
  "Syrian Arabepublic",
  "Taiwan,rovince of China",
  "Tajikistan",
  "Tanzania,nited Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad andobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks andaicos Islands",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arabmirates",
  "United Kingdom",
  "United States",
  "United Statesinor Outlying Islands",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela,olivarian Republic of",
  "Viet Nam",
  "Virgin IslandsBritish",
  "Virgin IslandsU.S.",
  "Wallis andutuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe"
];

export default countryList;
